logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO

---

spring:
  profiles: default, local


management:
  endpoint:
    health:
      show-details: always

route:
  datasource:
    -
      label: h2
      datasource-class-name: org.h2.jdbcx.JdbcDataSource
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;
      username: sa
      password:
    -
      label: mysql
      datasource-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      jdbc-url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC&pinGlobalTxToPhysicalConnection=true
      username: root
      password: 1234

---

spring:
  profiles: prod